### ISSUE TITLE
work ?

### ISSUE THREAD

**Issue by jims001** [Azzary/LeafMITM#1]
hi i want to know if the bot still work with mono serv

**Comment by Azzary** [comment]
I think that he works but there is no travel system (script)

**Comment by geranim0** [comment]
What are the steps to configure it? I get a NOT SANDBOXED but nothing works after that.

Do we need to change the ip and port for the server ones? other things to configure?

**Comment by Azzary** [comment]
the bot is not update, there is no ip to change normally if it does not work, it is exceeded
